### ISSUE TITLE
New Samples

### ISSUE THREAD

**Issue by nicolaslegland** [cubiclesoft/windows-pe-artifact-library#1]
As per [your request](https://discord.com/channels/777282089980526602/777282091041423384/1075940963752607865) please find attached [artifacts.zip](https://github.com/cubiclesoft/windows-pe-artifact-library/files/10762178/artifacts.zip) with "the rare PE artifacts + all the NE files + any interesting MZ files".

**Comment by cubiclesoft** [comment]
Thanks for the artifacts.  A: is an interesting drive letter.  That's usually reserved for floppy drives, which almost no one uses anymore.

As a side note, I found a few 5 1/4" floppies still sealed in original packaging as a result of yesterday's search through my archives.  I don't have any way to read them though.

Closing.
